### ISSUE TITLE
pgadmin4 1.4

### ISSUE THREAD

**Issue by ksamborski** [meedan/docker-hub#1]
Is there any chance to upgrade pgadmin to the newest version? I've found it is 1.4 now but the image still has 1.2. Here is the link: https://www.postgresql.org/ftp/pgadmin/pgadmin4/v1.4/pip/

**Comment by bnfinet** [comment]
done!

https://github.com/meedan/docker-hub/commit/a38f96cd582134632899674f23e65bed211ef6a2

if you should ever notice it to be out of date again, we're always happy to review a pull request.
